# Generated by Django 3.0.3 on 2020-07-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='name',
            field=models.TextField(default='0'),
        ),
    ]
