# Generated by Django 3.0.3 on 2020-07-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200710_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolsdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_name', models.CharField(max_length=256)),
                ('students_no', models.IntegerField()),
                ('locatioin', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='studentdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('locatioin', models.CharField(max_length=20)),
                ('sch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='todo.schoolsdb')),
            ],
        ),
    ]
